// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (*User, error)
	GetUsers(ctx context.Context) ([]*User, error)
	IsEmailTaken(ctx context.Context, email string) (int32, error)
	VerifyUser(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
