version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "secret"
    ports:
      - 15432:80
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  db-volume:

networks:
  backend:
    driver: bridge
